version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # MQTT alapértelmezett port
      - "9001:9001"  # WebSocket port (ha szükséges)
    volumes:
      - "./mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      - mqtt_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: home_automation
    ports:
      - "3306:3306"  # MySQL alapértelmezett port
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mqtt_network

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "5000:5000"  # Flask port
    depends_on:
      - mqtt
      - mysql
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge
