version: '3.8'

networks:
  mqtt_network:
    external: true

volumes:
  db_data:

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home_automation
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mqtt_network

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      - mqtt_network

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mqtt
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:rootpassword@db/home_automation
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    networks:
      - mqtt_network
